"""Model emission: every named object schema becomes a TypedDict.

TypedDict is the honest shape here, because :meth:`ApiClient.call_api` returns
parsed JSON. The annotation describes the dict a caller actually receives, with
no deserialization layer and no runtime cost, and type checkers can still catch a
misspelled key or a wrong field type.

All models land in one module so that cross-references never form an import
cycle and ``get_type_hints`` can always resolve a forward reference.
"""

from __future__ import annotations

import keyword
from typing import Any

from .naming import snake_case
from .schema_registry import SchemaRegistry

MODULE_HEADER = '''"""Models for {title}.

Generated by openapi-py-fetch. Do not edit by hand.
"""

from __future__ import annotations

'''


def generate_models_module(registry: SchemaRegistry, api_title: str) -> tuple[str, list[str]]:
    """Render every registered model into one module.

    Returns (module_source, model_names). Resolving one model's properties can
    name further models, so this keeps rendering until the registry stops
    growing.
    """
    rendered: dict[str, str] = {}
    while True:
        pending = sorted(name for name in registry.models if name not in rendered)
        if not pending:
            break
        for name in pending:
            rendered[name] = _render_model(name, registry.models[name], registry)

    names = sorted(rendered)
    if not names:
        return MODULE_HEADER.format(title=api_title) + "# No object schemas in this spec.\n", []

    body = "\n\n\n".join(rendered[name] for name in names)
    imports = _typing_imports(body)
    exports = "".join(f'    "{name}",\n' for name in names)

    source = MODULE_HEADER.format(title=api_title)
    if imports:
        source += f"from typing import {', '.join(imports)}\n\n"
    source += f"\n{body}\n\n\n__all__ = [\n{exports}]\n"
    return source, names


def _typing_imports(body: str) -> list[str]:
    """Which typing names the rendered models actually reference."""
    candidates = ("Any", "Literal", "NotRequired", "TypedDict")
    return [name for name in candidates if name in body]


def _render_model(name: str, schema: dict[str, Any], registry: SchemaRegistry) -> str:
    """Render one object schema as a TypedDict, in class or functional form."""
    properties = schema.get("properties") or {}
    required = set(schema.get("required") or [])

    fields: list[tuple[str, str]] = []
    for prop_name, prop_schema in properties.items():
        annotation = registry.python_type(prop_schema, name + _pascal_suffix(prop_name))
        if prop_name not in required:
            annotation = f"NotRequired[{annotation}]"
        fields.append((prop_name, annotation))

    doc = (schema.get("description") or f"{name} model.").strip().split("\n")[0][:200]

    if all(_is_identifier(prop_name) for prop_name, _ in fields):
        lines = [f"class {name}(TypedDict):", f'    """{doc}"""', ""]
        lines.extend(f"    {prop_name}: {annotation}" for prop_name, annotation in fields)
        return "\n".join(lines)

    entries = "".join(f'        "{prop_name}": {annotation},\n' for prop_name, annotation in fields)
    return f'{name} = TypedDict(\n    "{name}",\n    {{\n{entries}    }},\n)'


def _is_identifier(name: str) -> bool:
    return name.isidentifier() and not keyword.iskeyword(name)


def _pascal_suffix(prop_name: str) -> str:
    """Name hint for an inline schema nested under a property."""
    return "".join(part.capitalize() for part in snake_case(prop_name).split("_") if part)
