name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: pypi

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
